project:
  type: website
  output-dir: docs

website:
  title: "Micael"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd


# supplying a light ("minty") and dark ("slate") theme to toggle between
format:
  html:
    theme: lux
    css: styles.css


